data = [
    {'id': "0", 'name': 'Danse Macabre', 'icon': 'https://statics.bloodlibrary.info/img/icons/300025.gif', 'abbrv': 'dm',
     'cards': [{'name': 'Karif al Numair', 'amount': '2', 'id': '200754'},
               {'name': 'Mimir', 'amount': '2', 'id': '200991'},
               {'name': 'Mélusine d\'Anjou', 'amount': '2', 'id': '200974'},
               {'name': 'Gold Pan Dan', 'amount': '2', 'id': '200527'},
               {'name': 'Claudia', 'amount': '2', 'id': '200277'},
               {'name': 'Pearl', 'amount': '2', 'id': '201106'},
               {'name': 'Badr, Shadow of Granada', 'amount': '2', 'id': '200160'},
               {'name': 'Strohmann', 'amount': '2', 'id': '201320'},
               {'name': 'Synner-G', 'amount': '2', 'id': '201332'},
               {'name': 'Dark Selina', 'amount': '2', 'id': '200321'},
               {'name': 'Gerald FitzGerald', 'amount': '2', 'id': '200507'},
               {'name': 'Alex Camille', 'amount': '2', 'id': '200047'},
               {'name': 'Drozodny', 'amount': '2', 'id': '200389'},
               {'name': 'Skulk', 'amount': '2', 'id': '201297'},
               {'name': 'Carolina Vález', 'amount': '2', 'id': '200249'},
               {'name': 'Amber', 'amount': '2', 'id': '200067'},
               {'name': 'Righteous Endeavor', 'amount': '2', 'id': '201191'},
               {'name': 'Johannes Worringen', 'amount': '2', 'id': '200714'},
               {'name': 'Aimery Methuin', 'amount': '2', 'id': '200027'},
               {'name': 'Inside Dirt', 'amount': '4', 'id': '100990'},
               {'name': 'Dark Steel', 'amount': '4', 'id': '100495'},
               {'name': 'Marked Territory', 'amount': '3', 'id': '101170'},
               {'name': 'Recruitment Exercise', 'amount': '4', 'id': '101570'},
               {'name': 'Xipe Totec', 'amount': '2', 'id': '201482'},
               {'name': 'Ludmijla Rakoczy', 'amount': '2', 'id': '200879'},
               {'name': 'De Sade', 'amount': '2', 'id': '200327'},
               {'name': 'Instantaneous Transformation', 'amount': '4', 'id': '100994'},
               {'name': 'Shakar: the Hunt', 'amount': '4', 'id': '101749'},
               {'name': 'Esprit de Corps', 'amount': '3', 'id': '100663'},
               {'name': 'Public Vilification', 'amount': '4', 'id': '101514'},
               {'name': 'Spoils of War', 'amount': '4', 'id': '101854'},
               {'name': 'Shadow Boxing', 'amount': '4', 'id': '101736'},
               {'name': 'Show of Force', 'amount': '4', 'id': '101772'},
               {'name': 'Under Siege', 'amount': '4', 'id': '102063'}, ]},

    {'id': "1", 'name': 'The Unaligned 1', 'icon': 'https://statics.bloodlibrary.info/img/icons/300026.gif', 'abbrv': 'tu',
     'cards': [{'name': 'Mateusz Kazimirski, Biker of Blood', 'amount': '2', 'id': '200959'},
               {'name': 'Rebekah', 'amount': '2', 'id': '201170'},
               {'name': 'Zephyr', 'amount': '2', 'id': '102205'},
               {'name': 'Dam the Heart\'s River', 'amount': '4', 'id': '100489'},
               {'name': 'Hall of Mirrors', 'amount': '4', 'id': '100879'},
               {'name': 'Al-Ashrad, Amr of Alamut', 'amount': '2', 'id': '200036'},
               {'name': 'Priority Contract', 'amount': '4', 'id': '101487'},
               {'name': 'Flavia, Avenging Angel', 'amount': '2', 'id': '200469'},
               {'name': 'Omer', 'amount': '2', 'id': '201080'},
               {'name': 'Wise Frog', 'amount': '2', 'id': '201472'},
               {'name': 'Abid bin Haji, Scholar of Mirrors', 'amount': '2', 'id': '200007'},
               {'name': 'Enam', 'amount': '2', 'id': '200422'},
               {'name': 'Illusory Resources', 'amount': '4', 'id': '100955'},
               {'name': 'Sanguine Entrapment', 'amount': '4', 'id': '101679'},
               {'name': 'Imanna', 'amount': '2', 'id': '200630'},
               {'name': 'Suspension of Disbelief', 'amount': '4', 'id': '101911'},
               {'name': 'Skaald', 'amount': '1', 'id': '101789'},
               {'name': 'Ennoia\'s Theater', 'amount': '1', 'id': '100646'},
               {'name': 'Focus the Blood', 'amount': '4', 'id': '100753'},
               {'name': 'Dhita Choudhair', 'amount': '2', 'id': '200341'},
               {'name': 'Iago Castille', 'amount': '2', 'id': '200615'},
               {'name': 'Adri, the Seeker', 'amount': '2', 'id': '200015'},
               {'name': 'Karmenita Yoryari', 'amount': '2', 'id': '200756'},
               {'name': 'Bear\'s Skin', 'amount': '4', 'id': '100145'},
               {'name': 'Rewilding', 'amount': '2', 'id': '101632'},
               {'name': 'Dr. Lawrence Mayhew', 'amount': '2', 'id': '200380'},
               {'name': 'Vestgeir', 'amount': '2', 'id': '201437'},
               {'name': 'Ivan Krenyenko', 'amount': '2', 'id': '200649'},
               {'name': 'Sanjay Chakrabarti', 'amount': '2', 'id': '201233'},
               {'name': 'C.J.', 'amount': '2', 'id': '200230'},
               {'name': 'Rise of the Fallen', 'amount': '1', 'id': '101638'},
               {'name': 'Malcolm', 'amount': '2', 'id': '200902'},
               {'name': 'Delizbieta of the Dark Eyes', 'amount': '2', 'id': '200332'},
               {'name': 'Brunhilde', 'amount': '2', 'id': '200224'},
               {'name': 'Bulscu', 'amount': '1', 'id': '200227'},
               {'name': 'Winterlich', 'amount': '1', 'id': '201471'},
               {'name': 'Valkyrie', 'amount': '4', 'id': '201423'},
               {'name': 'Dr. Sutton Gassaway', 'amount': '2', 'id': '200384'},
               {'name': 'Claudio Severino', 'amount': '1', 'id': '200279'}, ]},

    {'id': "2", 'name': 'The Unaligned 2', 'icon': 'https://statics.bloodlibrary.info/img/icons/300026.gif', 'abbrv': 'tu',
     'cards': [{'name': 'Lisandro Giovanni', 'amount': '2', 'id': '200840'},
               {'name': 'Madeleine Giovanni', 'amount': '2', 'id': '200897'},
               {'name': 'Bez Dunsirn', 'amount': '2', 'id': '200195'},
               {'name': 'Dr. Oliver Genet', 'amount': '2', 'id': '200382'},
               {'name': 'Funeral Wake', 'amount': '4', 'id': '100797'},
               {'name': 'In Memory of the Two Lands', 'amount': '2', 'id': '100967'},
               {'name': 'Salvatore Giovanni', 'amount': '2', 'id': '201227'},
               {'name': 'Martino della Passaglia', 'amount': '2', 'id': '200944'},
               {'name': 'Giulia Giovanni Abruzzina', 'amount': '1', 'id': '100832'},
               {'name': 'Lupo Giovanni', 'amount': '2', 'id': '200888'},
               {'name': 'Domenic Giovanni', 'amount': '2', 'id': '200356'},
               {'name': 'Gianna di Canneto', 'amount': '1', 'id': '100823'},
               {'name': 'Nar-Sheptha', 'amount': '1', 'id': '101264'},
               {'name': 'Blight', 'amount': '4', 'id': '100187'},
               {'name': 'Ambrogino Giovanni', 'amount': '2', 'id': '200069'},
               {'name': 'Ophidian Gaze', 'amount': '4', 'id': '101325'},
               {'name': 'Spiritual Guidance', 'amount': '4', 'id': '101851'},
               {'name': 'Gift of Proteus', 'amount': '4', 'id': '100827'},
               {'name': 'Serpent\'s Numbing Kiss', 'amount': '4', 'id': '101727'},
               {'name': 'Count Jocalo', 'amount': '2', 'id': '200294'},
               {'name': 'Ghede', 'amount': '2', 'id': '200512'},
               {'name': 'Legba', 'amount': '2', 'id': '200828'},
               {'name': 'Sarrasine', 'amount': '2', 'id': '201243'},
               {'name': 'Saatet-ta', 'amount': '1', 'id': '101665'},
               {'name': 'Thing', 'amount': '4', 'id': '101972'},
               {'name': 'Elizabeth Dimitros', 'amount': '2', 'id': '200414'},
               {'name': 'Velvet Tongue', 'amount': '4', 'id': '102100'},
               {'name': 'Glycon', 'amount': '2', 'id': '200526'},
               {'name': 'Cao Nguyen', 'amount': '2', 'id': '200241'},
               {'name': 'Missy Shillingford', 'amount': '2', 'id': '200997'},
               {'name': 'Shahara al-Rashwa', 'amount': '2', 'id': '201272'},
               {'name': 'Inyanga', 'amount': '2', 'id': '200638'},
               {'name': 'Matasuntha', 'amount': '2', 'id': '200956'},
               {'name': 'Xaviar', 'amount': '2', 'id': '201478'},
               {'name': 'Claudio Severino', 'amount': '1', 'id': '200279'},
               {'name': 'Mark Decker', 'amount': '2', 'id': '200937'},
               {'name': 'Rosa Hernández', 'amount': '2', 'id': '201203'},
               {'name': 'Winterlich', 'amount': '1', 'id': '201471'},
               {'name': 'Rise of the Fallen', 'amount': '1', 'id': '101638'},
               {'name': 'Bulscu', 'amount': '1', 'id': '200227'},
               {'name': 'Art Morgan', 'amount': '2', 'id': '200142'}, ]},

    {'id': "3", 'name': 'Anarchs Unbound', 'icon': 'https://statics.bloodlibrary.info/img/icons/300027.gif', 'abbrv': 'au',
     'cards': [{'name': 'Tori Longwood', 'amount': '2', 'id': '201383'},
               {'name': 'Ariane', 'amount': '2', 'id': '200132'},
               {'name': 'Appolonius', 'amount': '2', 'id': '200126'},
               {'name': 'Marguerite Foccart', 'amount': '2', 'id': '200921'},
               {'name': 'Zack North', 'amount': '2', 'id': '201499'},
               {'name': 'Danielle Diron', 'amount': '2', 'id': '200317'},
               {'name': 'Dancin\' Dana', 'amount': '2', 'id': '200314'},
               {'name': 'Sundown', 'amount': '2', 'id': '201326'},
               {'name': 'Gengis', 'amount': '2', 'id': '200503'},
               {'name': 'Salvador Garcia', 'amount': '2', 'id': '201226'},
               {'name': 'Maldavis', 'amount': '2', 'id': '200904'},
               {'name': 'Jenna Cross', 'amount': '2', 'id': '200688'},
               {'name': 'Vulture', 'amount': '2', 'id': '201460'},
               {'name': 'Crow', 'amount': '2', 'id': '200303'},
               {'name': 'Philip van Vermeer IV', 'amount': '2', 'id': '201121'},
               {'name': 'Victor Gerard', 'amount': '2', 'id': '201439'},
               {'name': 'Irena', 'amount': '2', 'id': '200640'},
               {'name': 'Monica Chang', 'amount': '2', 'id': '201003'},
               {'name': 'Boss Callihan', 'amount': '2', 'id': '200213'},
               {'name': 'Medic, The', 'amount': '2', 'id': '200968'},
               {'name': 'Adhocracy', 'amount': '2', 'id': '100022'},
               {'name': 'Carfax Abbey', 'amount': '1', 'id': '100297'},
               {'name': 'Dust Up', 'amount': '3', 'id': '100597'},
               {'name': 'Desiree Narayan, Anarch Historian', 'amount': '2', 'id': '200338'},
               {'name': 'Javier Montoya', 'amount': '2', 'id': '200681'},
               {'name': 'Daliah', 'amount': '2', 'id': '200308'},
               {'name': 'Louis Fortier', 'amount': '2', 'id': '200863'},
               {'name': 'Field Training', 'amount': '2', 'id': '100725'},
               {'name': 'Bollix', 'amount': '3', 'id': '100232'},
               {'name': 'Donnybrook', 'amount': '3', 'id': '100576'},
               {'name': 'Hackerspace', 'amount': '2', 'id': '100876'},
               {'name': 'Legacy', 'amount': '2', 'id': '101085'},
               {'name': 'Memory Rift', 'amount': '2', 'id': '101199'},
               {'name': 'Ni Dieu ni Maître', 'amount': '2', 'id': '101282'},
               {'name': 'Eat the Rich', 'amount': '2', 'id': '100605'},
               {'name': 'Guardian Vigil', 'amount': '3', 'id': '100868'},
               {'name': 'Illegalism', 'amount': '3', 'id': '100952'},
               {'name': 'Protection Racket', 'amount': '2', 'id': '101501'},
               {'name': 'Netwar', 'amount': '2', 'id': '101275'},
               {'name': 'Make the Misere', 'amount': '3', 'id': '101147'},
               {'name': 'Propaganda of the Deed', 'amount': '3', 'id': '101496'},
               {'name': 'Red Question, The', 'amount': '2', 'id': '101575'}, ]},
]

for zet in data:
    zet['cards'].sort(key=lambda x: x['id'], reverse=True)
